# Format examples

> Source: https://developers.google.com/style/format-examples

To introduce an example in a sentence, use the guidance in the following table:

| Guidance | Recommended | Not recommended |
| --- | --- | --- |
| At the end of a sentence, use a comma or an em dash. | Enter a name for the instance, such as `my-instance-99`. Enter a name for the instance—for example, `my-instance-99`. | Enter a name for the instance, for example, `my-instance-99`. Enter a name for the instance; for example, `my-instance-99`. Enter a name for the instance (for example, `my-instance-99`). |
| In the middle of a sentence, use parentheses if the example is short. Otherwise, rewrite the sentence. | Enter a six-digit hex number (for example, `228B22`), and then click **OK**. Enter a six-digit hex number, such as `228B22`, and then click **OK**. Enter a six-digit hex number, and then click **OK**. For example, if you want the color forest green, enter `228B22`. | Enter a six-digit hex number (for example, if you want the color forest green, enter `228B22`), and then click **OK**. |

For more information, see [Parentheses](https://developers.google.com/style/parentheses).
