project:
  type: website
  output-dir: _site

website:
  title: "Google Documentation Style Guide"
  site-url: "https://tech-writing-lab.github.io/style-guide/"
  repo-url: "https://github.com/tech-writing-lab/style-guide"
  issue-url: "https://github.com/tech-writing-lab/style-guide/issues"
  repo-actions: edit # 顯示 Edit this page 和 report issue
  back-to-top-navigation: true
  # google-analytics: "G-VGGH88LLN9"
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        href: "https://github.com/tech-writing-lab/style-guide"
        text: GitHub

  sidebar:
      contents:
        - section: "Introduction"
          contents: 
            - text: "About this guide"
              href: content/en/introduction/about.qmd
            - text: "Highlights"
              href: content/en/introduction/highlights.qmd
            - text: "What's new"
              href: content/en/introduction/whats-new.qmd
            - text: "Philosophy of this guide"
              href: content/en/introduction/philosophy.qmd
        - section: "Key resources"
          contents: content/en/key-resources/*
        - section: "General principles"  
          contents: 
            - text: "Accessibility"
              href: content/en/general-principles/accessibility.qmd
            - text: "Excessive claims"
              href: content/en/general-principles/excessive-claims.qmd
            - text: "Future features"
              href: content/en/general-principles/future.qmd
            - text: "Global audience"
              href: content/en/general-principles/global-audience.qmd
            - text: "Inclusive language"
              href: content/en/general-principles/inclusive-language.qmd
            - text: "Jargon"
              href: content/en/general-principles/jargon.qmd
            - text: "Prescriptive documentation"
              href: content/en/general-principles/prescriptive-documentation.qmd
            - text: "Third-party content"
              href: content/en/general-principles/other-sources.qmd
            - text: "Timeless documentation"
              href: content/en/general-principles/timeless-documentation.qmd
            - text: "Voice and tone"
              href: content/en/general-principles/tone.qmd
        - section: "Language and grammar"
          contents:
            - text: "Abbreviations"
              href: content/en/grammar/abbreviations.qmd
            - text: "Active voice"
              href: content/en/grammar/voice.qmd
            - text: "Anthropomorphism"
              href: content/en/grammar/anthropomorphism.qmd
            - text: "Articles (a, an, the)"
              href: content/en/grammar/articles.qmd
            - text: "Capitalization"
              href: content/en/grammar/capitalization.qmd
            - text: "Contractions"
              href: content/en/grammar/contractions.qmd
            - text: "Plurals in parentheses"
              href: content/en/grammar/plurals-parentheses.qmd
            - text: "Possessives"
              href: content/en/grammar/possessives.qmd
            - text: "Prepositions"
              href: content/en/grammar/prepositions.qmd
            - text: "Present tense"
              href: content/en/grammar/tense.qmd
            - text: "Pronouns"
              href: content/en/grammar/pronouns.qmd
            - text: "Second person"
              href: content/en/grammar/person.qmd
            - text: "Sentence structure"
              href: content/en/grammar/sentence-structure.qmd
            - text: "Verbs in reference documents"          
              href: content/en/grammar/reference-verbs.qmd
        - section: "Punctuation"
          contents:
            - text: "Colons"
              href: content/en/punctuation/colons.qmd
            - text: "Commas"
              href: content/en/punctuation/commas.qmd
            - text: "Dashes"
              href: content/en/punctuation/dashes.qmd
            - text: "Ellipses"
              href: content/en/punctuation/ellipses.qmd
            - text: "Hyphens"
              href: content/en/punctuation/hyphens.qmd
            - text: "Parentheses"
              href: content/en/punctuation/parentheses.qmd
            - text: "Periods and end punctuation"
              href: content/en/punctuation/periods.qmd
            - text: "Quotation marks"
              href: content/en/punctuation/quotation-marks.qmd
            - text: "Semicolons"
              href: content/en/punctuation/semicolons.qmd
            - text: "Slashes"
              href: content/en/punctuation/slashes.qmd
        - section: "Formatting and organization"
          contents:
            - text: "Dates and times"
              href: content/en/formatting/dates-times.qmd
            - text: "Examples"
              href: content/en/formatting/format-examples.qmd
            - text: "Figures and other images"
              href: content/en/formatting/images.qmd
            - text: "Footnotes"
              href: content/en/formatting/footnotes.qmd
            - text: "Headings and titles"
              href: content/en/formatting/headings.qmd
            - text: "Italics with terms"
              href: content/en/formatting/italics-terms.qmd
            - text: "Lists"
              href: content/en/formatting/lists.qmd
            - text: "Notes and other notices"
              href: content/en/formatting/notices.qmd
            - text: "Numbers"
              href: content/en/formatting/numbers.qmd
            - text: "Paragraphs"
              href: content/en/formatting/paragraph-structure.qmd
            - text: "Phone numbers"
              href: content/en/formatting/phone-numbers.qmd
            - text: "Plural of a single letter"
              href: content/en/formatting/plural-single-letter.qmd
            - text: "Procedures"
              href: content/en/formatting/procedures.qmd
            - text: "Tables"
              href: content/en/formatting/tables.qmd
            - text: "Units of measurement"
              href: content/en/formatting/units-of-measure.qmd
        - section: "Linking"
          contents:
            - text: "Cross-references and linking"
              href: content/en/linking/cross-references.qmd
            - text: "Headings as link targets"
              href: content/en/linking/headings-targets.qmd
        - section: "Computer interfaces"
          contents:
            - text: "API reference code comments"
              href: content/en/computer-interfaces/api-reference-comments.qmd
            - text: "Code in text"
              href: content/en/computer-interfaces/code-in-text.qmd
            - text: "Code samples"
              href: content/en/computer-interfaces/code-samples.qmd
            - text: "Command-line syntax"
              href: content/en/computer-interfaces/code-syntax.qmd
            - text: "Placeholder formatting"
              href: content/en/computer-interfaces/placeholders.qmd
            - text: "UI elements and interaction"
              href: content/en/computer-interfaces/ui-elements.qmd
        - section: "HTML and CSS"
          contents:
            - text: "HTML and semantic tagging"
              href: content/en/html-css/semantic-tagging.qmd
            - text: "HTML formatting"
              href: content/en/html-css/html-formatting.qmd
            - text: "Markdown versus HTML"
              href: content/en/html-css/markdown.qmd
        - section: "Names and naming"
          contents:
            - text: "Example domains and names"
              href: content/en/naming/examples.qmd
            - text: "Filenames"
              href: content/en/naming/filenames.qmd
            - text: "Trademarks"
              href: content/en/naming/trademarks.qmd
  page-footer:
    right: "最後更新： 2025-10-05"

format:
  html:
    toc: true
    toc-expand: 2
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    grid:
      sidebar-width: 300px
    css: styles.css
    date-format: "YYYY-MM-DD"
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    # Note: English fonts must be first, otherwise single quote characters might be transformed to right curly quotes.
    mainfont: Roboto, "Noto Sans TC", -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"
    monofont: Menlo, Monaco, Consolas, SFMono-Regular, "Liberation Mono", "Courier New", monospace
    comments:
      giscus: 
        repo: tech-writing-lab/style-guide
