# Articles (a, an, the)

> Source: https://developers.google.com/style/articles

For ease of comprehension and translation, include definite and indefinite articles (*a*, *an*, and *the*) in your writing. Don't skip articles for brevity, including in headings and titles.

- ✅ Recommended: Create a VM instance

- ❌ Not recommended: Create VM instance

For more information about using standard English word order and about writing for a global audience in general, see [Write for a global audience](https://developers.google.com/style/translation).

For more information about writing clear headings and titles, see [Headings and titles](https://developers.google.com/style/headings).

For information about using articles before product names, see [Articles before product names](https://developers.google.com/style/product-names#the-with-names).

For information about using *a* or *an* before an abbreviation when the pronunciation of the abbreviation can vary, see [Indefinite articles before abbreviations](https://developers.google.com/style/abbreviations#articles).