# Pronouns

> Source: https://developers.google.com/style/pronouns

Ensure that a pronoun clearly refers to its antecedent (the noun that it's replacing).

## Ambiguous pronoun references

Avoid vague and confusing references between a pronoun and its antecedent.

- ✅ Recommended: If you type text in the field, the text doesn't change.

- ❌ Not recommended: If you type text in the field, it doesn't change.

- ✅ Recommended: The name of the function to execute in the given script. The name does not include parentheses or parameters.

- ❌ Not recommended: The name of the function to execute in the given script. It does not include parentheses or parameters.

In many cases, it's best to follow a demonstrative pronoun (like *this* and *these*) with a noun.

- ✅ Recommended: Set this value to true.

- ❌ Not recommended: Set this to true.

- ✅ Recommended: These approaches are your best options.

- ❌ Not recommended: These are your best options.

## Gender-neutral pronouns

Don't use gender-specific pronouns unless the person you're referring to is actually that gender.

In particular, don't use *he*, *him*, *his*, *she*, or *her* as gender-neutral pronouns, and don't use *he/she* or *(s)he* or other such punctuational approaches. Instead, use the singular *they*.

Singular *they* has been in use for a long time; for example, [Jane Austen used it](http://www.pemberley.com/janeinfo/austheir.html), and in 2015 the Washington Post[adopted it as part of their official style](https://www.washingtonpost.com/opinions/the-post-drops-the-mike--and-the-hyphen-in-e-mail/2015/12/04/ccd6e33a-98fa-11e5-8917-653b65c809eb_story.html).

For more suggestions, see The Chicago Manual of Style, 16th edition, section 5.225, "Nine techniques for achieving gender neutrality."

## Optional pronouns

To avoid ambiguity and clarify meaning in sentences, use optional pronouns such as *that* and *which*.

| Recommended | Not recommended |
| --- | --- |
| Right-click the link that you want to open. | Right-click the link you want to open. |
| You can use other option parameters, which are described in the following section. | You can use other option parameters, described in the following section. |

For more information, see [Relative pronouns](https://developers.google.com/style/pronouns#relative-pronouns).

## Personal pronouns

Avoid first-person pronouns (*I*, *we*, *us*, *our*, and *ours*) except in the following contexts:

- The questions in FAQs.
- A document whose author makes comments in the first person.
- Using *we* to refer to your organization, after using your organization's name. For example, "Example Pet Store recommends that you feed your aardvark Standardized Aardvark Treats. We cannot guarantee the happiness of your aardvark otherwise."

Use the second-person pronoun (*you*) whenever possible. For more information about second person, see [Second person and first person](https://developers.google.com/style/person).

## Relative pronouns

There are several relative pronouns. This section concerns only three of them: *that*, *which*, and *who*.

*That* and *which* don't mean exactly the same thing, so don't substitute one for the other:

- *That* introduces a restrictive clause. It isn't preceded by a comma. 
- ✅ Recommended: The echidna that has a long snout is furry.

This sentence describes a particular echidna, the one that has a long snout.

- *Which* introduces a nonrestrictive clause and is preceded by a comma. 
- ✅ Recommended: The echidna, which has a long snout, is furry.

This sentence describes all echidnas, and mentions in passing that they all have long snouts.

For more information about restrictive and nonrestrictive clauses and whether to use *that* or *which*, read [what Grammar Girl has to say on the subject](https://www.quickanddirtytips.com/articles/which-versus-that/).

When you're referring to a person, you can use *who* instead of *that*. If you're not sure which pronoun is appropriate in your context, then it's generally OK to use *that*.

You can use *whose* to refer to people, animals, and things. *Whose* is the possessive form of both *who* and *which*.

- ✅ Recommended: Examine the variables whose values are set at compile time.