# Semicolons

> Source: https://developers.google.com/style/semicolons

If possible, avoid using semicolons. In a few cases, a semicolon is preferred:

- When joining two closely related independent clauses where a period or a comma is not as effective.

- ✅ Recommended: You can easily test compatibility by computing the centroid; if it is on the opposite side of the planet, reverse the order of your vertices.

- When preceding a conjunctive adverb (like *therefore*) or a phrase (like *that is*) that joins two independent clauses.

- ✅ Recommended: This setup places the head-tracked node below the Main Camera; therefore, only the stereo cameras are affected by the user's head motion.

- ✅ Recommended: The URL from which a video ad loads; that is, the URL to use to fetch that video ad.

- When separating a series of long or complex items that contain their own punctuation.

- ✅ Recommended: If you don't have time, then focus on the improvements that will have the greatest benefit: what matters most to your users; what is most important to fix; and what is easy or feasible to fix in the available time.

- ✅ Recommended: Review your document one more time, checking for the following: present tense and active voice; typos, punctuation, and grammar; and whether you can shorten anything.

Notice that in the final example, the second item in the list is itself a list.